- name: ONTAP Setup and Storage Config for Oracle
  collections:
    - netapp.ontap
  hosts: "{{ hosts | default ('ontap') }}"
  connection: local
  gather_facts: False
  vars_files:
    - roles/ontap/defaults/main.yml    
    - vars/vars.yml
  vars_prompt:
    - name: vsadmin_password
      prompt: Enter vsadmin password for the SVM
      unsafe: yes
      private: yes
  roles:
    - role: ontap
  tags:
    - ontap_config

- name: Oracle Linux Setup and Storage Config for Oracle
  hosts: oracle
  gather_facts: False
  vars_files:
    - roles/linux/defaults/main.yml
    - vars/vars.yml
  roles:
    - role: linux
  tags:
    - linux_config

- name: Oracle installation and configuration
  hosts: oracle
  gather_facts: False
  vars_files:
    - roles/oracle/defaults/main.yml
    - roles/linux/defaults/main.yml
    - vars/vars.yml
  roles:
    - role: oracle
  tags:
    - oracle_config
