---
- name: Increase file descriptor hard limit
  lineinfile:
    path: /etc/security/limits.conf
    line: "*               hard    nofile          65536"
  become: true

- name: Increase min stack size
  lineinfile:
    path: /etc/security/limits.conf
    line: "*               soft    stack           10240"
  become: true
