---
- name: Disable SELinux
  selinux: state=disabled
  become: true
  tags:
    - disable_selinux

- name: Disable firewall deamon (firewalld)
  service: name=firewalld state=stopped enabled=no
  become: true
  tags:
    - disable_firewall
