---
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# This playbook contains all the plays for oracle-linux 8.2 tasks.
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------

- block:
    - name: Create mount points for NFS file systems
      include_tasks: mount_points.yml
      tags:
        - cre_mount_points
        - mount_host_datastores
          
- block:
    - name: Install required packages, create oracle user and groups
      include_tasks: preinstall_rpm.yml
      tags:
        - preinstall_rpm
- block:
    - name: Create Oracle base directories
      include_tasks: create_database.yml
      tags:
        - oracle_base
        - oracle_data
        - oracle_reco
- block:
    - name: Disable transparent hugepages and configure kernel for hugepages
      include_tasks: huge_pages.yml
      tags:
        - disable_thp
        - config_hugepages
- block:
    - name: Disable firewall deamon/SELinux
      include_tasks: disable_se.yml
      tags:
        - disable_selinux
        - disable_firewall
- block:
    - name: Update ntp servers to chronyd, default ntp servers not working
      include_tasks: update_ntp.yml
      tags:
        - update_ntp_server
- block:
    - name: Increase file descriptor hard limit
      include_tasks: descriptor_limit.yml
- block:
    - name:  Create a pam.d session file
      include_tasks: session_files.yml
