---
- name: Update ntp servers to chronyd, default ntp servers not working
  replace:
    path: /etc/chrony.conf
    regexp: '^server {{ item }}.ol.pool.ntp.org iburst'
    replace: 'server {{ item }}.us.pool.ntp.org iburst'
  loop:
    - 0
    - 1
    - 2
    - 3
  become: true
  tags:
    - update_ntp_server

- name: Restart chronyd service
  service:
    name: chronyd
    state: restarted
  become: true
