---
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Generate a target dbca.rsp file at template dest to work around 'invalid selinux context' issue
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Generate a target dbca.rsp file at template dest to work around 'invalid selinux context' issue
      file:
        path: "{{ installation_folder }}/dbca.rsp"
        state: touch
      become: true
      become_user: '{{ oracle_user }}'
      tags:
        - gen_dbca_rsp_si
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Generate a target dbca.rsp file at template dest to work around 'invalid selinux context' issue] FAILED. Hints:"
          - 1. Check the failure error message
          - 2. Check vars file to ensure there is no discrepancy in the variable declaration
          - 3. Ensure that there is no residual configuration on the switch that can cause failure of this task
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Generate response file for dbca for single instance Oracle setup
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Generate response file for dbca for single instance Oracle setup
      template:
        src: "dbca.rsp.{{ ora_version }}"
        dest: "{{ installation_folder }}/dbca.rsp"
      become: true
      become_user: '{{ oracle_user }}'
      tags:
        - gen_dbca_rsp_si
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Generate response file for dbca for single instance Oracle setup] FAILED. Hints:"
          - 1. Check the failure error message
          - 2. Check vars file to ensure there is no discrepancy in the variable declaration
          - 3. Ensure that there is no residual configuration on the switch that can cause failure of this task
 # ----------------------------------------------------------------------------------------------------------------------
 # ----------------------------------------------------------------------------------------------------------------------
 # Create database for single Oracle instance
 # ----------------------------------------------------------------------------------------------------------------------
 # ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Create database for single Oracle instance
      command: "{{ oracle_home }}/bin/dbca -silent -createDatabase -responseFile {{ installation_folder }}/dbca.rsp"
      become: true
      become_user: '{{ oracle_user }}'
      tags:
        - exec_dbca_si
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Create database for single Oracle instance] FAILED. Hints:"
          - 1. Check the failure error message
          - 2. Check vars file to ensure there is no discrepancy in the variable declaration
          - 3. Ensure that there is no residual configuration on the switch that can cause failure of this task
