---
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Generate an Aggreate list to use for the SVM Creation
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- vars:
    aggr_list: []
  block:
    - name: Generate the aggr list variable for Oracle SVM
      set_fact:
        aggr_list: "{{ aggr_list + [item.aggr_name] }}"
      with_items:
        - "{{ data_aggregates }}"
      failed_when: item.aggr_name == None or item.aggr_name == ""
  tags:
    - ontap_config_svm
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Generate the aggr list variable for Oracle SVM] FAILED. Hints:"
          - 1. Check the failure error message
          - 2. Check vars file to ensure there is no discrepancy in the variable declaration
          - 3. Ensure that there is no residual configuration on the switch that can cause failure of this task

- block:      
    - name: See the avaialble aggr list
      debug: var=aggr_list 
  tags:
    - ontap_config_svm
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [See the avaialble aggr list] FAILED. Hints:"
          - 1. Check the failure error message
          - 2. Check vars file to ensure there is no discrepancy in the variable declaration
          - 3. Ensure that there is no residual configuration on the switch that can cause failure of this task

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Create SVM with NFS protocol
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:      
    - name: Create Oracle data SVM with NFS protocols enabled
      na_ontap_svm: 
        hostname: "{{ inventory_hostname }}" 
        username: "{{ username }}"
        password: "{{ password }}" 
        state: present 
        name: "{{ svm_name }}"
        root_volume: "{{ svm_name }}_root"
        root_volume_aggregate: "{{ data_aggregates[0].aggr_name }}"
        root_volume_security_style: unix 
        aggr_list: "{{ aggr_list }}" 
        https: true 
        validate_certs: false
  tags:
    - ontap_config_svm
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Create Oracle data SVM with NFS protocols enabled] FAILED. Hints:"
          - 1. Check the failure error message
          - 2. Check vars file to ensure there is no discrepancy in the variable declaration
          - 3. Ensure that there is no residual configuration on the switch that can cause failure of this task

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Enable NFS Protocol for SVM
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:      
    - name: Enable NFS protcol for Oracle SVM
      na_ontap_nfs: 
        hostname: "{{ inventory_hostname }}" 
        username: "{{ username }}" 
        password: "{{ password }}" 
        state: present 
        vserver: "{{ svm_name }}" 
        vstorage_state: enabled 
        service_state: started
        udp: disabled 
        https: true 
        validate_certs: false
  tags:
    - ontap_config_svm
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Enable NFS protcol for Oracle SVM] FAILED. Hints:"
          - 1. Check the failure error message
          - 2. Check vars file to ensure there is no discrepancy in the variable declaration
          - 3. Ensure that there is no residual configuration on the switch that can cause failure of this task

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Create the load-sharing mirror volumes for the root volume
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Create the load-sharing mirror volumes for the Oracle root volume
      na_ontap_volume: 
        hostname: "{{ inventory_hostname }}" 
        username: "{{ username }}" 
        password: "{{ password }}" 
        state: present 
        vserver: "{{ svm_name }}"
        name: "{{ item.1.root_mirror_volume }}"
        aggregate_name: "{{ item.0.aggr_name }}" 
        size: 1 
        type: DP 
        https: true 
        validate_certs: false
      with_together:
        - "{{ data_aggregates }}"
        - "{{ root_mirror_volumes }}"
  tags:
    - ontap_ls_mirror_volumes      
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Create the load-sharing mirror volumes for the Oracle root volume] FAILED. Hints:"
          - 1. Check the failure error message
          - 2. Check vars file to ensure there is no discrepancy in the variable declaration
          - 3. Ensure that there is no residual configuration on the switch that can cause failure of this task

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Create Job schedule for the root volume snapmirror
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Create a job schedule for the snapmirror of root volume
      na_ontap_job_schedule: 
        hostname: "{{ inventory_hostname }}" 
        username: "{{ username }}" 
        password: "{{ password }}"
        state: present 
        name: "{{ item.job_name }}"
        job_minutes: "{{ item.job_minutes }}"
        https: true 
        validate_certs: false
      with_items:
        - "{{ job_schedule }}"
  tags:
    - ontap_config_job_schedule
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Create a job schedule for the snapmirror of root volume] FAILED. Hints:"
          - 1. Check the failure error message
          - 2. Check vars file to ensure there is no discrepancy in the variable declaration
          - 3. Ensure that there is no residual configuration on the switch that can cause failure of this task

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Create the SnapMirror relationship between root volume and mirror volumes (new format)
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
#- block:
#    - name: Create the SnapMirror relationships
#      na_ontap_snapmirror:
#        hostname: "{{ inventory_hostname }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        state: present
#        source_endpoint:
#          cluster: "{{ source_cluster }}"
#          path: "{{ svm_name }} : {{ svm_root_volume }}"
#        destination_endpoint:
#          cluster: "{{ destination_cluster }}"
#          path: "{{ svm_name }} : {{item.root_mirror_volume }}"      
#        relationship_type: load_sharing
#        schedule: "{{ job_schedule.0.job_name }}"
#        https: true
#        validate_certs: false
#      with_items:
#        - "{{ root_mirror_volumes }}"
#  tags:
#    - ontap_snapmirror_relationship
#  rescue:
#    - name: Failure message
#      debug:
#        msg:
#          - "TASK [Create the SnapMirror relationships] FAILED. Hints:"
#          - 1. Check the failure error message
#          - 2. Check vars file to ensure there is no discrepancy in the variable declaration
#          - 3. Ensure that there is no residual configuration on the switch that can cause failure of this task

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Create the SnapMirror relationship between root volume and mirror volumes
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Create the SnapMirror relationships
      na_ontap_snapmirror:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        source_volume: "{{ svm_root_volume }}"
        destination_volume: "{{ item.root_mirror_volume }}"
        source_vserver: "{{ svm_name }}"
        destination_vserver: "{{ svm_name }}"
        relationship_type: load_sharing
        schedule: "{{ job_schedule.0.job_name }}"
        https: true
        validate_certs: false
      with_items:
        - "{{ root_mirror_volumes }}"
  tags:
    - ontap_snapmirror_relationship
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Create the SnapMirror relationships] FAILED. Hints:"
          - 1. Check the failure error message
          - 2. Check vars file to ensure there is no discrepancy in the variable declaration
          - 3. Ensure that there is no residual configuration on the switch that can cause failure of this task

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Initialize the snapmirror relationship
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Initialize the mirroring relationship
      na_ontap_snapmirror:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        source_path: "{{ svm_name }}:{{ svm_root_volume }}"
        destination_path: "{{ svm_name }}:{{ item.root_mirror_volume }}"
        https: true
        validate_certs: false
      with_items:
        - "{{ root_mirror_volumes }}"
  tags:
    - ontap_snapmirror_relationship
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Initialize the mirroring relationship] FAILED. Hints:"
          - 1. Check the failure error message
          - 2. Check vars file to ensure there is no discrepancy in the variable declaration
          - 3. Ensure that there is no residual configuration on the switch that can cause failure of this task

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Initialize the mirroring relationship
#- block:
#    - name: Initialize the mirroring relationship
#      na_ontap_snapmirror:
#        hostname: "{{ inventory_hostname }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        state: present
#        source_endpoint:
#          path: "{{ svm_name }} : {{ svm_root_volume }}"
#        destination_endpoint:
#          path: "{{ svm_name }} : {{item.root_mirror_volume }}"
#        https: true
#        validate_certs: false
#      with_items:
#        - "{{ root_mirror_volumes }}"
#  tags:
#    - ontap_snapmirror_relationship
#  rescue:
#    - name: Failure message
#      debug:
#        msg:
#          - "TASK [Initialize the mirroring relationship] FAILED. Hints:"
#          - 1. Check the failure error message
#          - 2. Check vars file to ensure there is no discrepancy in the variable declaration
#          - 3. Ensure that there is no residual configuration on the switch that can cause failure of this task

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Set the password for vsadmin first. Account cannot be unlocked without password
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Set password for vsadmin user
      na_ontap_user:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        vserver: "{{ svm_name }}"
        applications: http,ontapi,ssh
        authentication_method: password
        role_name: vsadmin
        lock_user: yes
        name: vsadmin
        set_password: "{{ vsadmin_password }}"
        https: true
        validate_certs: false
  tags:
    - ontap_unlock_svm_admin
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Set password for vsadmin user] FAILED. Hints:"
          - 1. Check the failure error message
          - 2. Check vars file to ensure there is no discrepancy in the variable declaration
          - 3. Ensure that there is no residual configuration on the switch that can cause failure of this task

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Unlock vsadmin user (This is the SVM admin account)
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Unlock vsadmin user
      na_ontap_user:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        vserver: "{{ svm_name }}"
        applications: http,ontapi,ssh
        authentication_method: password
        role_name: vsadmin
        lock_user: no
        name: vsadmin
        https: true
        validate_certs: false
  tags:
    - ontap_unlock_svm_admin
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Unlock vsadmin user] FAILED. Hints:"
          - 1. Check the failure error message
          - 2. Check vars file to ensure there is no discrepancy in the variable declaration
          - 3. Ensure that there is no residual configuration on the switch that can cause failure of this task

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Create LIF for SVM Management            
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:      
    - name: Create LIF for Oracle SVM Management
      na_ontap_interface:
        hostname: "{{ inventory_hostname }}" 
        username: "{{ username }}" 
        password: "{{ password }}" 
        state: present 
        vserver: "{{ svm_name }}"
        role: data 
        protocols: none 
        home_node: "{{ node_data_ports[0].node_name }}" 
        home_port: "{{ item.home_port }}"
        address: "{{ item.address }}" 
        netmask: "{{ item.netmask }}"
        interface_name: "{{ item.lif_name }}" 
        admin_status: up 
        failover_policy: broadcast-domain-wide 
        firewall_policy: mgmt 
        is_auto_revert: true 
        https: true 
        validate_certs: false
      with_items:
        - "{{ svm_specs }}"
  tags:
    - ontap_svm_mgmt_lif
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Create LIF for Oracle SVM Management] FAILED. Hints:"
          - 1. Check the failure error message
          - 2. Check vars file to ensure there is no discrepancy in the variable declaration
          - 3. Ensure that there is no residual configuration on the switch that can cause failure of this task

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------	  
